---

- name: fisrt config
  hosts: vxlanleaf
  vars:
    nxos_provider:
      username: "{{ user }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ inventory_hostname }}"



  tasks:

    - name: config hostname
      nxos_config:
        lines: hostname {{ inventory_hostname }}
        provider: "{{ nxos_provider }}"
        save_when: modified

    - name: enable feature
      nxos_feature:
        feature: '{{ item.feature }}'
        provider: "{{ nxos_provider }}"
      with_items: "{{ features }}"

    - name: add vlan
      nxos_vlans:
        config:
          - vlan_id: 10
            name: test-vlan10-l2
            mapped_vni: 10010
          - vlan_id: 20
            name: test-vlan20-l2
            mapped_vni: 10020
          - vlan_id: 100
            name: l3-vni
            mapped_vni: 10100

        







