---

- name: fisrt config
  hosts: vxlanleaf
  vars:
    nxos_provider:
      username: "{{ user }}"
      password: "{{ pwd }}"
      transport: cli
      host: "{{ inventory_hostname }}"



  tasks:

    - name: config hostname
      nxos_config:
        lines: hostname {{ inventory_hostname }}
        provider: "{{ nxos_provider }}"
        save_when: modified

    - name: enable feature
      nxos_feature:
        feature: '{{ item.feature }}'
        provider: "{{ nxos_provider }}"
      with_items: "{{ features }}"
    - name: enable nv overlay evpn
      nxos_evpn_global:
        nv_overlay_evpn: true

    - name: add vlan
      nxos_vlans:
        config:
          - vlan_id: 10
            name: test-vlan10-l2
            mapped_vni: 10010
          - vlan_id: 20
            name: test-vlan20-l2
            mapped_vni: 10020
          - vlan_id: 100
            name: l3-vni
            mapped_vni: 10100


    - name: interface agg
      nxos_lag_interfaces:
        config:
          - name: port-channel10
            members:
              - member: Ethernet1/1
                mode: active
              - member: Ethernet1/2
                mode: active

    - name: config interface and port-channel
      nxos_interfaces:
        config:
          - name: Port-channel10
            description: To-Spine
            mtu: 9216
            mode: layer3
            enabled: true
          - name: vlan100
            ip_forward: true
          - name: vlan10
            fabric_forwarding_anycast_gateway: true
          - name: vlan20
            fabric_forwarding_anycast_gateway: true

    - name: add vrf
      nxos_vrf:
        name: vlan100
        state: present

    - name: apply vrf
      nxos_vrf:
        name: vlan100
        interfaces:
          - vlan10
          - vlan20
          - vlan100

    - name: config ip
      nxos_l3_interfaces:
        config:
          - name: loopback0
            ipv4:
              - address: 1.1.1.1/32
          - name: loopback1
            ipv4:
              - address: 100.1.1.1/24
          - name: vlan10
            ipv4:
              - address: 10.1.1.1/24
          - name: vlan20
            ipv4:
              - address: 20.1.1.1/24
          - name: port-channel10
            ipv4:
              - address: 21.1.1.1/24

    - name: config pim rp
      nxos_pim_rp_address:
        rp_address: 100.1.1.1

    - name: enable interface pim
      nxos_pim_interface:
        interface: port-channel10
        sparse: true











        







